### PR TITLE
remove android actionbar

### PR DESCRIPTION
**Pull request by m1ga**
Remove the Anroid Action bar for the TiShadow App

### CODE REVIEW

**Comment by dbankier** [comment]
Thanks. 

Instead of applying the no action bar theme across the application you might want to just apply it to the `StartScreen.js` instead. I would like to keep the default behaviour for the container app and for anything fancier (themes/modules/etc) leave that to the `--appify` or `--shadow` path.

**Comment by m1ga** [comment]
sure, can do that too. I always find it strange to do it in Javascript because you'll see the actionbar for a splitsecond and then it will disappear. Its nicer when it has a custom theme. I'll change the commit later today

**Comment by dbankier** [comment]
You can set the theme with the theme property when creating the window so the Action Bar shouldn't show.






On Thu, Feb 12, 2015 at 1:20 AM -0800, "Michael" <notifications@github.com> wrote:












sure, can do that too. I always find it strange to do it in Javascript because you'll see the actionbar for a splitsecond and then it will disappear. Its nicer when it has a custom theme. I'll change the commit later today

**Comment by m1ga** [comment]
added it to the styles of the startup window (working) but I wasn't sure about the actual app (UI.js). If I set args.theme = "Theme.NoActionBar"; (line 41) it will remove it but a app where I have a custom action won't show it either.

**Comment by dbankier** [comment]
merged. thanks.

**Pull request merged**
