### PR TITLE
Make boost feature to compile all changed files at once

### PR DESCRIPTION
**Pull request by yomybaby**
## Notice
This PR is dpends on https://github.com/appcelerator/alloy/pull/803.
Before https://github.com/appcelerator/alloy/pull/803 is merged, never allow this PR. :) I'll keep my eyes on Alloy PR and let you know.

## Background and Description
Tishadow boost is so fast. But there is a bad case.
When modify several files and save all at once, `ts @ run -u` build only one controller. So to apply all changes, you should run `ts run` addtionally.
I just want make to compile all changed files at once without addtional excute `run` command.

### CODE REVIEW

**Comment by gimdongwoo** [comment]
Very good!!
Right!
[When modify several files and save all at once, ts @ run -u build only one controller.]
This is big trouble.

**Comment by gimdongwoo** [comment]
sudo npm install -g yomybaby/alloy#restrictFiles
sudo npm install -g yomybaby/TiShadow#alloy_compile_boost

I've tested it, it works perfectly.

**Comment by gimdongwoo** [comment]
Alloy PR merged and released, a day ago 👍 
https://github.com/appcelerator/alloy/releases

**Comment by gimdongwoo** [comment]
@dbankier Merge, please.

**Comment by dbankier** [comment]
@gimdongwoo, just waiting for a response to my comment.

**Comment by yomybaby** [comment]
@dbankier Any problem? :)

**Comment by dbankier** [comment]
Just curious why you removed sourcemap=false?

**Comment by yomybaby** [comment]
`alloy compile --config platform=ios,sourcemap=false` make a source map file even `sourcemap=false` options exists.
Only `"sources":false` on `app/config.json`file works properly.
I'm not sure this is a bug or spec.
Do you have any idea about this?

I just removed it because it doesn't affect at all.

**Comment by dbankier** [comment]
Understood. Merging for now. Will look into it. Thanks.
I think it did work previously and was included to speed things up further...

**Comment by gimdongwoo** [comment]
👍
meery Christmas.

**Comment by yomybaby** [comment]
🎅 :mrs_claus:  🎄 🎁

**Pull request merged**
