### PR TITLE
Add support sourcemap

### PR DESCRIPTION
**Pull request by rotorgames**
This will work now to ios.

In some cases, android shows no line errors.

Also, it will not work if the error in `require`.

All these problems are solved here: https://github.com/appcelerator/titanium_mobile/pull/6901

If the titanium will Pull Request everything will work perfectly!

- [X] Test Android emulator
- [X] Test Android device
- [X] Test IOS emulator
- [ ] Test IOS device

### CODE REVIEW

**Comment by dbankier** [comment]
Cool! So I don't need to wait on the titanium PR?
I will test this out soon.

**Comment by rotorgames** [comment]
@dbankier I'll make another Pull Request for tishadow, that he could work with my assembly titanium. And I will give reference to the assembly titanium. Then you can test the full.

**Comment by yomybaby** [comment]
Cool! :+1:

**Comment by rotorgames** [comment]
@dbankier 
The branch where the work customResourceDirectory, and sourcemap: https://github.com/rotorgames/TiShadow/tree/test_require

Titanium sdk build: https://cloud.mail.ru/public/Hn6z/QkzFLVEME

**Comment by dbankier** [comment]
Just testing on iOS (without the custom SDK) and doesn't seem to work... Will look again later.

**Comment by rotorgames** [comment]
@dbankier Checked, it does not really work. The console does not show sourceURL, therefore determine the file where the error was impossible.
Try my build of titaium sdk.

**Comment by rotorgames** [comment]
It took six months. Appcelerator Titanium did not approve my Pull Request (https://github.com/appcelerator/titanium_mobile/pull/6901), and vryatli approve. Probably, Appcelerator is not beneficial to troubleshoot problems with tishadow. I am extremely disappointed.

Exactly six months ago, I stopped using Titanium, and videmo not in vain.
Attitudes toward people who want to help, terrible. (https://github.com/appcelerator/titanium_mobile/pull/6896)

They still have not accepted my PullRequest, 2 lines of code that solves problems with WebView.

I'm disappointed in Titanium, and I do not regret that no longer developed on Appcelerator Titanium.

**Comment by dbankier** [comment]
Sorry to hear. What are you using now?

**Comment by rotorgames** [comment]
@dbankier Xamarin. There are no such problems in Appcelerator titanium, and the problems that there are, are solved very quickly, without Pull Request.

Too bad, I liked the Titanium, but it roll into the abyss.

**Pull request closed without merging**
