### PR TITLE
Make tishadow watch files by extension.

### PR DESCRIPTION
**Pull request by sg552**
hi  dbankier,

  My team is using coffee-script, every time the coffee file changed, the tishadow will trigger a new compile. 
  It's impossible to add the 'compile coffeescript' process to the alloy.jmk's "pre:compile", because this will make the "Alloy compile" infinite. 

  So I added an option "fileTypesToWatch" to the tishadow configure, usage is quite simple:

```json
// edit ~/.tishadow.json
{
  "fileTypesToWatch": "**/*.{js, tss, xml}"
}
```

  This will make tishadow only watch "js/tss/xml" files' change, and will of course ignore the 'coffee files' change.  

thanks 
Siwei

### CODE REVIEW

**Comment by dbankier** [comment]
Nice idea. 

The code however will break a few things (https://github.com/dbankier/TiShadow/pull/408/files#diff-935b28ad0757a15868811be4cadb49e7R222), e.g. it will break watching i18n files, won't watch for assets, etc.

If you are using other precompilers, you probably want to keep the `app/` directory clean and have your `coffee` files in a `src/` directory. 

Have a look how I restructured https://github.com/dbankier/JAST recently.
That uses Jade for views, STSS for styles and ES6 for controllers.

**Comment by sg552** [comment]
OK, thanks!

**Comment by sg552** [comment]
@dbankier, I followed your suggestion , and now using "spec" folder to keep all my unit test files, however every time I change my "spec file", the Tishadow app restarts which is unnecessary and cost time. 

The scenario is : 
1. in terminal 1: I start my project using tishadow, and it works great:  

    $ titanium build --platform android --target device --shadow

2. in terminal 2: I write spec files and then run it, it works great, too: 

    $ tishadow spec -t mocha-should --platform android

3. everytime I change my "spec_files" content, what I need to do is just re-run the command in "Terminal 2",  The problem is: the tishadow process in "Terminal 1" will re-compile and then restart the app. this is unnecessary. this takes long time. (about 8 seconds to compile)

So, I use the code from this pull request, and then changed my ~/.tishadow.json:

{
  "port": 3333,
  ....
  "fileTypesToWatch": "app/**/*"
}

and it works!  It no longer watch the 'spec' folder anymore.

so, what do you think about this pull request ? ^_^

**Comment by dbankier** [comment]
1.

**Comment by dbankier** [comment]
1. Your spec issue is solved if you use the _update_ flag with it.
2. I'd prefer this PR to be `exclude` instead of `include`, otherwise it breaks too many things as mentioned in the first comment.

**Comment by sg552** [comment]
OK.  I will change my commit to `exclude`

**Comment by dbankier** [comment]
Just pushed this commit: https://github.com/dbankier/TiShadow/commit/cac7251d754d8592a6d2aec276a950af8c482da0
It gives you what you want.

**Pull request closed without merging**
