### PR TITLE
Under Windows, replace backslash with forward slash

### PR DESCRIPTION
**Pull request by gaspardle**

### CODE REVIEW

**Comment by dbankier** [comment]
Thanks for the pr. Why do you have backslashes in your Ti code?

**Comment by gaspardle** [comment]
I don't have backslash in my code, but `path.join` with add them on windows

**Comment by dbankier** [comment]
ahh.... ok. Odd, as I have used it on Windows previously without the fix...

**Comment by gaspardle** [comment]
It does work, but not when the path is relative.

`var MyClass= require("./myfile");`

will be transformed to:
`var MyClass= __p.require("ile\\android\\Resources\\android\\myfile");`
instead of 
`var MyClass= __p.require("android/myfile");`

**Comment by gaspardle** [comment]
It does work, but not when the path is relative.

`var MyClass= require("./myfile");`

will be transformed to:
`var MyClass= __p.require("ile\\android\\Resources\\android\\myfile");`
instead of 
`var MyClass= __p.require("android/myfile");`

**Comment by dbankier** [comment]
Ok. Understood. I never use relative paths. 
Thank you.

**Pull request merged**
