### PR TITLE
Server host history

### PR DESCRIPTION
**Pull request by yomybaby**
This PR improves #498 .
Now there is host history list with current IP address of device.
:)
img_0504

### CODE REVIEW

**Comment by dbankier** [comment]
Thanks @yomybaby again and again. Do you want to be added as a maintainer?

**Comment by yomybaby** [comment]
Wow, It's an honor. 😄 
Thanks!

**Comment by dbankier** [comment]
No problem. I just need help balancing maintaining my open source projects with other responsibilities. You contribute quite a bit and seem to "get it".

**Comment by yomybaby** [comment]
🙏🏼

**Pull request merged**
