### PR TITLE
Include latest binary of DynamicFont

### PR DESCRIPTION
**Pull request by kopiro**

### CODE REVIEW

**Comment by dbankier** [comment]
Thanks. In future `appify.js` needs to be updated too. Did it for you.

**Comment by kopiro** [comment]
Sorry, I didn't get that :)

**Comment by dbankier** [comment]
https://github.com/dbankier/TiShadow/commit/1a5ca078328cb8a25d8d740162f4079432e0591a

**Comment by kopiro** [comment]
Yes, I browsed commits and I get that, but I did not know I had to do it :+1:

**Pull request merged**
