### PR TITLE
In appify app, you can change tishadow host. (shake & change)

### PR DESCRIPTION
**Pull request by yomybaby**
When ip address of localhost(tishadow server) is changed, We have to re-appify and build to device.

In this situation, just shake device to open window for change host.

img_8980

### CODE REVIEW

**Comment by gimdongwoo** [comment]
Awesome for cafe developer 👍

**Comment by dbankier** [comment]
Great idea as always. Perhaps we can make it optional, controlled by a flag? Or disabled for production builds? (I know of some appified apps in the appstore).

**Comment by yomybaby** [comment]
OK! I'll be back ~ 👍

**Comment by yomybaby** [comment]
It'll work when dev & test build only.

**Comment by dbankier** [comment]
Nice. Thanks.

**Pull request merged**
