### PR TITLE
SDK 7.0.0 support

### PR DESCRIPTION
**Pull request by darknos**
SDK 7.0.0 support

I'm not sure but it would be probably better to raise major version number. say 3.0.0 :)

### CODE REVIEW

**Comment by dbankier** [comment]
Thanks for doing all that. Happy with a dot changes as TiShadow itself hasn't change much with the modules updates.

**Comment by m1ga** [comment]
@darknos there was a little bug in the 7.0.0.GA autoupdate of modules: it will remove the description of the modules like: 
https://github.com/dbankier/TiShadow/pull/541/files#diff-3dcc0b53a5c892e7ff7302b2d70fd21aR8

**Comment by darknos** [comment]
I'm afraid I should leave old modules in app and manage versions in appify procedure.

Otherwise it will work only with SDK 7 projects for android.

**Comment by darknos** [comment]
> @darknos there was a little bug in the 7.0.0.GA autoupdate of modules: it will remove the description of the modules like:
https://github.com/dbankier/TiShadow/pull/541/files#diff-3dcc0b53a5c892e7ff7302b2d70fd21aR8

I see. I used automated conversion with "ti build" - it's their bug :)

**Comment by m1ga** [comment]
it is yes, should be fixed in 7.0.1 (https://jira.appcelerator.org/browse/TIMOB-25592)

**Comment by dbankier** [comment]
Just a thought. Can't we solve the pre-post 7 version issue by just including the pre and post versions of the modules and not include a fixed version number in the tiapp.xml?
Going to do that  now...

**Comment by dbankier** [comment]
Yep it works. Code pushed to master

**Pull request merged**
